import mongoose from "mongoose";
import bcrypt from "bcrypt";
import { Admin } from "./models/Admin";
import { Ingredient } from "./models/Ingredient";
import { Pizza } from "./models/Pizza";

const MONGO_URI = process.env["MONGO_URI"] ?? "mongodb://localhost:27017/forno";

const ingredients = [
  { type: "base", name: "Classic Hand Tossed", image: "", currentStock: 45, maxCapacity: 50, lowStockThreshold: 20, unit: "units", price: 0, isAvailable: true },
  { type: "base", name: "Thin Crust", image: "", currentStock: 8, maxCapacity: 50, lowStockThreshold: 20, unit: "units", price: 20, isAvailable: true },
  { type: "base", name: "Cheese Burst", image: "", currentStock: 32, maxCapacity: 50, lowStockThreshold: 20, unit: "units", price: 50, isAvailable: true },
  { type: "base", name: "Whole Wheat", image: "", currentStock: 28, maxCapacity: 50, lowStockThreshold: 20, unit: "units", price: 30, isAvailable: true },
  { type: "base", name: "Gluten Free", image: "", currentStock: 15, maxCapacity: 50, lowStockThreshold: 20, unit: "units", price: 40, isAvailable: true },
  { type: "sauce", name: "Classic Tomato", image: "", currentStock: 40, maxCapacity: 50, lowStockThreshold: 15, unit: "portions", price: 0, isAvailable: true },
  { type: "sauce", name: "BBQ Sauce", image: "", currentStock: 12, maxCapacity: 50, lowStockThreshold: 15, unit: "portions", price: 20, isAvailable: true },
  { type: "sauce", name: "White Garlic", image: "", currentStock: 35, maxCapacity: 50, lowStockThreshold: 15, unit: "portions", price: 20, isAvailable: true },
  { type: "sauce", name: "Pesto", image: "", currentStock: 22, maxCapacity: 50, lowStockThreshold: 15, unit: "portions", price: 30, isAvailable: true },
  { type: "sauce", name: "Spicy Arrabbiata", image: "", currentStock: 18, maxCapacity: 50, lowStockThreshold: 15, unit: "portions", price: 15, isAvailable: true },
  { type: "cheese", name: "Mozzarella", image: "", currentStock: 15, maxCapacity: 50, lowStockThreshold: 25, unit: "portions", price: 0, isAvailable: true },
  { type: "cheese", name: "Cheddar", image: "", currentStock: 30, maxCapacity: 50, lowStockThreshold: 25, unit: "portions", price: 20, isAvailable: true },
  { type: "cheese", name: "Four Cheese Blend", image: "", currentStock: 25, maxCapacity: 50, lowStockThreshold: 25, unit: "portions", price: 50, isAvailable: true },
  { type: "cheese", name: "Vegan Cheese", image: "", currentStock: 10, maxCapacity: 50, lowStockThreshold: 25, unit: "portions", price: 40, isAvailable: true },
  { type: "vegetable", name: "Bell Peppers", image: "", currentStock: 38, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 25, isAvailable: true },
  { type: "vegetable", name: "Mushrooms", image: "", currentStock: 18, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 30, isAvailable: true },
  { type: "vegetable", name: "Onions", image: "", currentStock: 42, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 15, isAvailable: true },
  { type: "vegetable", name: "Olives", image: "", currentStock: 35, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 25, isAvailable: true },
  { type: "vegetable", name: "Tomatoes", image: "", currentStock: 40, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 20, isAvailable: true },
  { type: "vegetable", name: "Jalapeños", image: "", currentStock: 5, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 20, isAvailable: true },
  { type: "vegetable", name: "Spinach", image: "", currentStock: 30, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 25, isAvailable: true },
  { type: "vegetable", name: "Sweet Corn", image: "", currentStock: 28, maxCapacity: 50, lowStockThreshold: 10, unit: "portions", price: 20, isAvailable: true },
];

const pizzas = [
  { name: "Classic Pepperoni Pizza", image: "/images/1_Pepperoni_pizza.png", description: "A timeless bestseller featuring generous slices of smoky pepperoni on a bed of rich tomato sauce and melted mozzarella cheese. The perfect balance of savory and spicy flavors with a crispy crust edge.", basePrice: 349, category: "non-veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Pepperoni", "Mozzarella Cheese", "Tomato Sauce", "Pizza Dough", "Oregano"], isAvailable: true, orderCount: 420 },
  { name: "Hot Diablo Pizza", image: "/images/2_The_Hot_Diablo_Pizza_Ooni_Australi.png", description: "A fiery delight for spice lovers! Features spicy pepperoni with a kick of chili, topped on a perfectly charred crust. The bold heat combined with savory meat makes this an intense flavor experience.", basePrice: 399, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Spicy Pepperoni", "Chili Flakes", "Mozzarella Cheese", "Tomato Sauce", "Basil", "Hot Sauce"], isAvailable: true, orderCount: 315 },
  { name: "Four Cheese Pizza (Quattro Formaggi)", image: "/images/3_Four_Cheese_Pizza_with_a_Side_Salad.png", description: "A vegetarian masterpiece loaded with four distinct cheeses - mozzarella, cheddar, parmesan, and gorgonzola. Creamy, rich, and indulgent with a beautiful golden crust.", basePrice: 379, category: "veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Mozzarella", "Cheddar", "Parmesan", "Gorgonzola", "Tomato Sauce", "Basil", "Olive Oil"], isAvailable: true, orderCount: 298 },
  { name: "Chicken Supreme Pizza", image: "/images/4_Chicken_Supreme_Pizza_Recipe.png", description: "A loaded non-vegetarian pizza featuring tender grilled chicken pieces, bell peppers, onions, and mushrooms on a cheesy base. A complete meal with protein and veggies in every bite.", basePrice: 429, category: "non-veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Grilled Chicken", "Bell Peppers", "Onions", "Mushrooms", "Mozzarella Cheese", "Tomato Sauce", "Black Olives"], isAvailable: true, orderCount: 387 },
  { name: "Vegan Margherita Pizza", image: "/images/5_Vegan_Margherita_Pizza_with_Cashew.png", description: "A plant-based twist on the classic Margherita featuring cashew mozzarella, fresh tomatoes, and basil on a perfectly baked crust. Dairy-free, cruelty-free, and absolutely delicious.", basePrice: 329, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Cashew Mozzarella", "Fresh Tomatoes", "Basil Leaves", "Tomato Sauce", "Olive Oil", "Pizza Dough"], isAvailable: true, orderCount: 189 },
  { name: "Veggie Supreme Pizza", image: "/images/6_Veggie_Supreme_Pizza.png", description: "The ultimate vegetarian pizza loaded with fresh vegetables including bell peppers, onions, tomatoes, mushrooms, olives, and corn. A colorful, nutritious, and flavorful choice for veggie lovers.", basePrice: 359, category: "veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Bell Peppers", "Onions", "Tomatoes", "Mushrooms", "Black Olives", "Corn", "Mozzarella Cheese", "Tomato Sauce"], isAvailable: true, orderCount: 276 },
  { name: "Spicy Chicken & Pickled Jalapeño Pizza", image: "/images/7_Spicy_Chicken_and_Pickled_Jalapeno.png", description: "A bold fusion pizza combining tender chicken with tangy pickled jalapeños and fresh cilantro. The pickled peppers add a unique sour-spicy kick that elevates the entire flavor profile.", basePrice: 419, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Chicken", "Pickled Jalapeños", "Cilantro", "Mozzarella Cheese", "Tomato Sauce", "Red Onion", "Lime"], isAvailable: true, orderCount: 254 },
  { name: "Rising Crust Pepperoni Pizza", image: "/images/8_Signature_SELECT_Pizza_Rising_Crust.png", description: "A thick, fluffy rising crust pizza topped with generous pepperoni and a blend of mozzarella and smoked gouda. The self-rising dough creates a satisfyingly thick and airy base.", basePrice: 409, category: "non-veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Pepperoni", "Mozzarella Cheese", "Smoked Gouda", "Tomato Sauce", "Rising Crust Dough"], isAvailable: true, orderCount: 301 },
  { name: "Meat Supreme Pizza", image: "/images/9_Meat_Supreme_Pizza_Anya_s_Pizza.png", description: "A carnivore's dream loaded with multiple meats including pepperoni, sausage, bacon, and ham. Rich, hearty, and supremely satisfying for meat lovers seeking the ultimate protein-packed pizza.", basePrice: 459, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Pepperoni", "Italian Sausage", "Bacon", "Ham", "Mozzarella Cheese", "Tomato Sauce", "Onions"], isAvailable: true, orderCount: 267 },
  { name: "Diablo Pepperoni Pizza", image: "/images/10_Diablo_Pepperoni_Pizza_Recipe_Ooni.png", description: "An intensely spicy pepperoni pizza featuring thick-cut spicy pepperoni rounds and fresh basil on a wood-fired crust. The charred edges and bold flavors make this a standout choice for heat seekers.", basePrice: 399, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Spicy Pepperoni", "Fresh Basil", "Mozzarella Cheese", "Tomato Sauce", "Chili Oil", "Wood-Fired Crust"], isAvailable: true, orderCount: 243 },
  { name: "Sausage, Bacon & Green Pepper Pizza", image: "/images/1_Sausage_Pizza_with_Onions_Green_Peppers.png", description: "A hearty non-vegetarian pizza loaded with Italian sausage, crispy bacon, and fresh green peppers on a golden crust. The smoky meat flavors pair perfectly with the sweet crunch of peppers.", basePrice: 409, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Italian Sausage", "Bacon", "Green Peppers", "Mozzarella Cheese", "Tomato Sauce", "Onions"], isAvailable: true, orderCount: 198 },
  { name: "Mediterranean Veggie Pizza", image: "/images/2_Veggie_Pizza_Vegetarian_Pizza_Recipe.png", description: "A vibrant vegetarian pizza inspired by Mediterranean flavors with roasted vegetables, olives, artichokes, and feta cheese. Fresh, healthy, and bursting with sunny flavors.", basePrice: 369, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Roasted Vegetables", "Kalamata Olives", "Artichoke Hearts", "Feta Cheese", "Mozzarella", "Tomato Sauce", "Oregano"], isAvailable: true, orderCount: 176 },
  { name: "Paneer Tikka Pizza", image: "/images/3_Paneer_Tikka_Pizza_made_from_scratch.png", description: "An Indian-fusion spicy pizza featuring tandoori-spiced paneer cubes, onions, and bell peppers. The aromatic tikka marinade brings bold flavors to this vegetarian delight.", basePrice: 369, category: "veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Paneer Cubes", "Tikka Marinade", "Onions", "Bell Peppers", "Mozzarella Cheese", "Tomato Sauce", "Cilantro"], isAvailable: true, orderCount: 289 },
  { name: "Truffle Mushroom Pizza", image: "/images/4_Easy_Truffle_Pizza_Recipe.png", description: "A gourmet vegetarian pizza featuring wild mushrooms, truffle oil, and fresh herbs on a thin crust. Earthy, aromatic, and elegantly simple - a true umami bomb.", basePrice: 449, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Wild Mushrooms", "Truffle Oil", "Mozzarella Cheese", "Parmesan", "Fresh Thyme", "Garlic", "Olive Oil"], isAvailable: true, orderCount: 165 },
  { name: "Garden Fresh Pizza", image: "/images/5_GARDEN_FRESH_VEGGIE_PIZZA_Butter.png", description: "A farm-to-table vegetarian pizza bursting with garden-fresh tomatoes, olives, peppers, and herbs. Light, refreshing, and packed with natural vegetable flavors.", basePrice: 339, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Fresh Tomatoes", "Black Olives", "Green Peppers", "Red Onions", "Mozzarella Cheese", "Tomato Sauce", "Fresh Basil"], isAvailable: true, orderCount: 187 },
  { name: "Spinach & Feta Pizza", image: "/images/6_spinach_and_feta_pizza.png", description: "A Mediterranean-inspired vegetarian pizza with sautéed spinach, creamy feta cheese, and garlic on a crispy crust. Nutritious, flavorful, and satisfyingly cheesy.", basePrice: 349, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Sautéed Spinach", "Feta Cheese", "Mozzarella", "Garlic", "Olive Oil", "Pizza Dough", "Black Pepper"], isAvailable: true, orderCount: 201 },
  { name: "Meat Lover's Pizza", image: "/images/7_Meat_Lover_s_Pizza_with_five_different.png", description: "The ultimate meat feast with five different types of meat - pepperoni, sausage, bacon, ham, and ground beef. A protein powerhouse that satisfies every carnivorous craving.", basePrice: 479, category: "non-veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Pepperoni", "Italian Sausage", "Bacon", "Ham", "Ground Beef", "Mozzarella Cheese", "Tomato Sauce"], isAvailable: true, orderCount: 345 },
  { name: "Spinach Ricotta Pizza", image: "/images/8_Spinach_Feta_Pizza.png", description: "A creamy vegetarian pizza featuring fresh spinach, ricotta cheese dollops, and mozzarella on a golden crust. The ricotta adds a luxurious creaminess to every bite.", basePrice: 359, category: "veg" as const, isCustom: false, tags: [], ingredients: ["Fresh Spinach", "Ricotta Cheese", "Mozzarella", "Garlic", "Olive Oil", "Pizza Dough", "Nutmeg"], isAvailable: true, orderCount: 154 },
  { name: "Paneer Tikka Masala Pizza", image: "/images/9_Paneer_Tikka_Masala_Pizza_Expert.png", description: "A bold Indo-Italian fusion with paneer cubes in rich tikka masala sauce, onions, and cilantro. Spicy, creamy, and uniquely flavorful - a bestseller for adventurous eaters.", basePrice: 389, category: "veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Paneer Cubes", "Tikka Masala Sauce", "Onions", "Cilantro", "Mozzarella Cheese", "Green Chilies"], isAvailable: true, orderCount: 312 },
  { name: "Festive Sausage, Bacon & Parma Ham Pizza", image: "/images/10_Festive_Sausage_Bacon_and_Parma_Ham.png", description: "A luxurious non-vegetarian pizza combining Italian sausage, crispy bacon, and delicate Parma ham. Three distinct pork flavors create a rich, savory symphony.", basePrice: 469, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Italian Sausage", "Bacon", "Parma Ham", "Mozzarella Cheese", "Tomato Sauce", "Fresh Basil"], isAvailable: true, orderCount: 178 },
  { name: "Tandoori Chicken Pizza", image: "/images/1_Tandoori_Chicken_Pizza_Spicy_Fusion.png", description: "An Indian-inspired spicy pizza with tandoori-marinated chicken, onions, and green chilies. The smoky tandoori flavor combined with melted cheese is absolutely irresistible.", basePrice: 439, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Tandoori Chicken", "Red Onions", "Green Chilies", "Mozzarella Cheese", "Tandoori Sauce", "Cilantro"], isAvailable: true, orderCount: 334 },
  { name: "Shrimp Scampi Pizza", image: "/images/2_Shrimp_Scampi_Pizza.png", description: "A seafood lover's dream featuring garlic butter shrimp, lemon zest, and parsley on a thin crust. Light, fresh, and ocean-inspired with a beautiful golden finish.", basePrice: 489, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Garlic Butter Shrimp", "Lemon Zest", "Fresh Parsley", "Mozzarella Cheese", "Olive Oil", "Garlic"], isAvailable: true, orderCount: 143 },
  { name: "Hawaiian Pizza", image: "/images/3_Hawaiian_Pizza_Recipe_With_Ham_Pineappl.png", description: "A controversial yet beloved bestseller combining sweet pineapple chunks with savory ham on a cheesy base. The sweet-salty contrast makes it surprisingly addictive.", basePrice: 379, category: "non-veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Ham", "Pineapple Chunks", "Mozzarella Cheese", "Tomato Sauce", "Pizza Dough"], isAvailable: true, orderCount: 309 },
  { name: "Capricciosa Pizza", image: "/images/4_Capricciosa_with_Roasted_Ham_Mushrooms.png", description: "A classic Italian non-vegetarian pizza with ham, mushrooms, artichokes, and olives on a thin crust. Each bite offers a different texture and flavor combination.", basePrice: 419, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Ham", "Mushrooms", "Artichoke Hearts", "Black Olives", "Mozzarella Cheese", "Tomato Sauce", "Fresh Basil"], isAvailable: true, orderCount: 187 },
  { name: "Peri Peri Chicken Pizza", image: "/images/5_Peri_Peri_Chicken_Pizza_Nando_s_Inspired.png", description: "A Nando's-inspired spicy pizza featuring peri peri marinated chicken, roasted peppers, and red onions. The African-Portuguese peri peri sauce brings serious heat and flavor.", basePrice: 449, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Peri Peri Chicken", "Roasted Peppers", "Red Onions", "Mozzarella Cheese", "Peri Peri Sauce", "Cilantro"], isAvailable: true, orderCount: 276 },
  { name: "Chicago Delight Cheese Burst Pizza", image: "/images/6_Chicago_Delight_Cheese_Burst_Pizza.png", description: "An indulgent vegetarian bestseller with a cheese-stuffed crust that oozes melted mozzarella with every bite. Loaded with extra cheese layers for the ultimate cheese lover's experience.", basePrice: 419, category: "veg" as const, isCustom: false, tags: ["bestseller"], ingredients: ["Mozzarella Cheese", "Cheddar Cheese", "Cream Cheese", "Tomato Sauce", "Cheese-Stuffed Crust", "Oregano"], isAvailable: true, orderCount: 387 },
  { name: "Garlic Shrimp Pizza", image: "/images/7_Shrimp_Scampi_Pizza.png", description: "A seafood specialty featuring plump garlic shrimp, melted mozzarella, and fresh herbs on a crispy thin crust. The garlic butter base makes this incredibly aromatic and delicious.", basePrice: 479, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Garlic Shrimp", "Mozzarella Cheese", "Fresh Parsley", "Garlic Butter", "Lemon Juice", "Pizza Dough"], isAvailable: true, orderCount: 143 },
  { name: "Classic Capricciosa", image: "/images/8_What_Is_Capricciosa_Pizza_Toppings.png", description: "The traditional Italian Capricciosa with roasted ham, mushrooms, and a perfectly baked egg in the center. Rustic, hearty, and authentically Italian.", basePrice: 429, category: "non-veg" as const, isCustom: false, tags: [], ingredients: ["Roasted Ham", "Mushrooms", "Baked Egg", "Mozzarella Cheese", "Tomato Sauce", "Black Olives", "Artichokes"], isAvailable: true, orderCount: 156 },
  { name: "Buffalo Chicken Pizza", image: "/images/9_Buffalo_Chicken_Pizza.png", description: "A spicy American classic featuring buffalo sauce-coated chicken, blue cheese crumbles, and celery-inspired freshness. The tangy heat of buffalo sauce is perfectly balanced by creamy cheese.", basePrice: 439, category: "non-veg" as const, isCustom: false, tags: ["spicy"], ingredients: ["Buffalo Chicken", "Blue Cheese Crumbles", "Mozzarella Cheese", "Buffalo Sauce", "Ranch Drizzle", "Green Onions"], isAvailable: true, orderCount: 267 },
  { name: "Peri Peri BBQ Chicken Pizza", image: "/images/10_Peri_peri_barbecue_chicken_pizza.png", description: "A bestseller fusion combining peri peri spice with sweet BBQ sauce, grilled chicken, and colorful peppers. The sweet-spicy balance makes this an absolute crowd favorite.", basePrice: 459, category: "non-veg" as const, isCustom: false, tags: ["spicy", "bestseller"], ingredients: ["Peri Peri BBQ Chicken", "Red Onions", "Bell Peppers", "Mozzarella Cheese", "BBQ Sauce", "Peri Peri Drizzle"], isAvailable: true, orderCount: 402 },
];

async function seed(): Promise<void> {
  // Never clobber a live database: the seed wipes pizzas/ingredients/admins.
  if (process.env["NODE_ENV"] === "production" && process.env["FORCE_SEED"] !== "true") {
    throw new Error("Refusing to seed in production. Set FORCE_SEED=true to override.");
  }

  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  await Admin.deleteMany({});
  await Ingredient.deleteMany({});
  await Pizza.deleteMany({});

  const adminPassword = process.env["ADMIN_PASSWORD"] ?? "Admin@123";
  const hashed = await bcrypt.hash(adminPassword, 12);
  await Admin.create({ name: "Forno Admin", email: "admin@forno.com", password: hashed });
  console.log(`Admin seeded — email: admin@forno.com / password: ${process.env["ADMIN_PASSWORD"] ? "from ADMIN_PASSWORD env" : "Admin@123"}`);

  await Ingredient.insertMany(ingredients);
  console.log(`${ingredients.length} ingredients seeded`);

  await Pizza.insertMany(pizzas);
  console.log(`${pizzas.length} pizzas seeded`);

  console.log("Seed complete!");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
